version: "3.4"
services: 
    text-analyzer:
        container_name: text-analyzer
        image: text-analyzer
        build: 
            context: ../text-analyzer
        volumes: 
            - ../text-analyzer:/app/text-analyzer
        ports: 
            - "8000:8000"
        command: sh -c "python3 /app/text-analyzer/manage.py runserver 0.0.0.0:8000"
        restart: on-failure
        healthcheck:
            test: curl --fail http://localhost:8000/health/ || exit 1
            interval: 5s
            retries: 5
            start_period: 2s
            timeout: 2s

    app-database:
        container_name: app-database
        build:
            context: ./database
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 10242048
        volumes:
            - ~/.social-app-docker/app-database/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    
    app-client:
        container_name: app-client
        image: app-client
        build:
            context: ../social-app-client
        depends_on: 
            - app-server
        volumes:
            - ../social-app-client:/app/client
            - /app/clinet/node_modules
        ports:
            - "3081:3000"
        command: bash -c "yarn start"

    app-server:
        container_name: app-server
        image: app-server
        build:
            context: ../social-app-server
        depends_on:
            - app-database
            - text-analyzer
        volumes:
          - "../social-app-server:/app/server"
        ports:
          - "9090:9090"
          - "5005:5005"
        command: bash -c "mvn spring-boot:run -Dspring.profiles.active=dev -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\""
        restart: on-failure
        healthcheck:
            test: curl --fail http://app-server:9090/actuator/health || exit 1
            interval: 5s
            retries: 5
            start_period: 2s
            timeout: 2s

    app-local-nginx:
        container_name: app-local-nginx
        image: app-local-nginx
        build:
            context: local-nginx
        ports:
            - "3080:80"
        volumes:
            - ./local-nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app-server
            - app-client
        restart: unless-stopped
        command: "supervisord -n"
