text-analyzer-server: http://text-analyzer:8000/api

spring:
  datasource:
    url: jdbc:postgresql://app-database:5432/social_media
    username: postgres
    password: 10242048

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always

server:
  port: 9090

logging:
  level:
    root: info
    com:
      kamrul:
        server: trace
    org:
      hibernate:
        type: trace
